public class datefunc {
    public static void daaata(){
        //public String formatGmt(String 'dateFormatString');
       /* public Date dateGMT(ss,m,hh,dd,mm,yyyy);
        //System.debug('************ ' + date.today().format());
		//Date ltDate = Date.newInstance('07:08:55 5-feb-2016');
		//Integer DD = stDate.daysBetween(ltdate);
		DateTime stdate;
        DateTime ltdate ;
		stdate = DateTime.newInstance();
        	Date myDate = myDateTime.dateGMT();
        ltdate = DateTime.newInstance(07,08,55,5,'feb',2016);
        	//Date myDate = myDateTime.dateGMT();
*/
       // DateTime myDateTime = DateTime.newInstance(06,07,55,2,'jan',2016);
		//String formatted = myDateTime.formatGMT('HH:mm:ss MMM d yyyy ');
		//String expected = '06,07,55,2,'jan',2016';
		//System.assertEquals(expected, formatted);
        

    }    
}